Big data is often automatically generated by a machine.
빅데이터는 자주 기계에 의해 자동으로 생성된다.
Instead of a person being involved in creating new data, it’s generated purely by machines in an automated way.
새로운 데이터를 만들어 내는 데 사람이 연관되는 대신, 그것은 자동적인 방식으로 순수하게 기계에 의해 생성된다.
If you think about traditional data sources, there was always a person involved.
여러분이 전통적인 데이터 원천을 생각한다면, 항상 연관된 사람이 있었다.
Consider retail or bank transactions, telephone call detail records, product shipments, or invoice payments.
소매나 은행 거래, 전화 통화의 세부 내용 기록, 제품 배송, 혹은 송장 지불을 생각해 보라.
All of those involve a person doing something in order for a data record to be generated.
이러한 모든 것은 데이터 기록이 만들어지기 위해 뭔가를 하는 사람을 수반한다.
Somebody had to deposit money, or make a purchase, or make a phone call, or send a shipment, or make a payment.
누군가는 돈을 예치하거나 구매하거나, 전화하거나, 배송품을 보내거나, 혹은 지불을 해야 했다.
In each case, there is a person who is taking action as part of the process of new data being created.
각각의 경우, 새로운 데이터가 만들어지는 과정의 일부로서 동작하는 사람이 있었다.
This is not so for big data in many cases.
많은 경우 빅데이터에는 이것이 적용되지 않는다.
A lot of sources of big data are generated without any human interaction at all.
빅데이터의 많은 원천은 인간의 상호작용이 전혀 없이도 생성된다.
A sensor embedded in an engine, for example, spits out data about its surroundings even if nobody touches it or asks it to.
예를 들어, 엔진에 설치된 센서는 아무도 그것을 만지거나 그것에게 그렇게 하도록 요구하지 않아도 그것의 주변 환경에 관한 데이터를 뱉어낸다.
