const erc11_8 = (req, res) => {
  res.json([
    {
      title: '8번',
      en: 'Living below a noisy neighbor can be trying, but what generally is the cause of the noise? ',
      ko: '시끄러운 이웃 아래에서 사는 것은 괴로울 수 있는데, 일반적으로 소음의 원인은 무엇일까? ',
    },
    {
      title: '8번',
      en: 'Most of the irritating noise is described as “thuds” or “thumps” and, perhaps surprisingly, is not due to something like high heels clicking on the floor. ',
      ko: '짜증나는 소음 대부분이 ‘쿵’ 또는 ‘탁’으로 묘사되며, 의외로 바닥에서 하이힐이 짤까닥거리는 것과 같은 것 때문이 아닐 수도 있다. ',
    },
    {
      title: '8번',
      en: 'Rather it is due to low-frequency noise generated by someone walking across the floor. ',
      ko: '오히려 그것은 누군가 바닥을 가로질러 걸어갈 때 발생하는 저주파 소음 때문이다. ',
    },
    {
      title: '8번',
      en: 'The repeated footfalls cause the floor to oscillate like a drumhead, typically at a frequency between 15 and 35 hertz, which is at the low-frequency end of the audible range for most people. ',
      ko: '반복되는 발소리는 북 가죽처럼 바닥을 일반적으로 15~35 헤르츠 사이의 진동수로 진동시키는데, 그것은 대부분의 사람들이 들을 수 있는 저주파수 범위의 끝에 있다. ',
    },
    {
      title: '8번',
      en: 'Such noise can be heard, and even felt, by the downstairs neighbor. ',
      ko: '그런 소음은 아래층 이웃이 들을 수 있고 심지어 느낄 수도 있다. ',
    },
    {
      title: '8번',
      en: 'The high-frequency sound of heels clicking on a floor might be heard, but far more energy is transferred to the drum-like, low-frequency floor oscillations. ',
      ko: '신발 굽이 바닥에서 짤까닥거리는 고주파 소리가 들릴 수도 있지만, 훨씬 더 많은 에너지가 드럼과 같은 저주파 바닥 진동으로 전환된다. ',
    },
    {
      title: '8번',
      en: 'Installing a carpet might actually worsen the situation because, with its softer surface, the footfalls can then transfer even more energy into the floor oscillations.',
      ko: '카펫을 설치하는 것이 실제로는 그 상황을 더 악화시킬 수 있는 데, 그 이유는 그러면 더 부드러운 표면으로 인해 발소리가 훨씬 더 많은 에너지를 바닥 진동으로 전환할 수 있기 때문이다. ',
    },
    {
      title: '8번',
      en: 'Generally the frequency of the most annoying noises from upstairs neighbors is (A)low, and laying a carpet on the floor might (B)increase noises since the footfalls can then transfer more energy into the floor oscillations.',
      ko: '일반적으로 가장 거슬리는 위층 이웃의 소음의 진동수는 낮으며, 카펫을 바닥에 까는 것은 발소리가 바닥 진동으로 더 많 은 에너지를 전환할 수 있으므로 소음을 증가시킬 수도 있다. ',
    },
  ]);
};
module.exports = { erc11_8 };
