name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd cntextbook-server/
            git pull https://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@github.com/jhyunwoo/cntextbook-server.git
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm install
            pm2 restart 0
            
      - name: send custom message with args
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: ${{ github.actor }} 님, 변경 내용 배포 완료.
